filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true
      add_error_key: true
  - timestamp:
      field: timestamp
      layouts:
        - '2006-01-02T15:04:05.999999999Z07:00'
      test:
        - '2025-12-29T18:51:17.223635Z'

output.elasticsearch:
  hosts: 'elasticsearch:9200'
  username: '${ELASTIC_USERNAME:}'
  password: '${ELASTIC_PASSWORD:}'

setup.kibana:
  host: "kibana:5601"
